config/routes.rb
Rails.application.routes.draw do

    root "posts#index"

    get "/users" => "users#index", as: :users
    get "/users/new" => "users#new", as: :new_user
    post "/users" => "users#create", as: :create_user

    get "/posts" => "posts#index", as: :posts
    get "/posts/new" => "posts#new", as: :new_post
    post "/posts" => "posts#create", as: :create_post

    get "/sessions/new" => "sessions#new", as: :new_session
    post "/sessions" => "sessions#create", as: :create_session
    get "/sessions/destroy" => "sessions#destroy", as: :destroy_session


end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_secure_password
    validates :email, presence: true, uniqueness: { case_sensitive: false }

    has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    unless current_user
        flash["alert-warning"] = "You must be logged in to view that page"
        redirect_to new_session_path
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        user = User.where( email: user_params[:email] ).first
        if user && user.authenticate(user_params[:password])
            session[:user_id] = user.id
            flash["alert-success"] = "You have been logged in"
            redirect_to posts_path
        else
            flash["alert-warning"] = "Improper login, please try again"
            redirect_to new_session_path
        end
    end

    def destroy
        session[:user_id] = nil
        flash["alert-success"] = "You have logged out"
        redirect_to posts_path 
    end

private

    def user_params
        params.require(:user).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        if User.create(user_params).valid?
            flash["alert-success"] = "You have been registered"
            redirect_to users_path
        else
            flash["alert-warning"] = "Unable to register you"
            redirect_to new_user_path
        end
    end

private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog With Comments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
</head>
<body class="container-fluid">

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1 class="jumbotron">Welcome to the DTLA WDI Blog</h1>

<% if @posts.count > 0 %>
    <% @posts.each do |post| %>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><%= post.title %></h3>
                <h6>Posted by: <%= post.user.name %>&nbsp;&nbsp;<small><%= post.updated_at%></small></h6>
            </div>
            <div class="panel-body">
                <p><%= post.body %></p>
            </div>
        </div>
    <% end %>
<% else %>
    <h2>No Posts Exist</h2>
<% end %>

<h1 class="jumbotron">Welcome to the DTLA WDI Blog</h1>

<% if current_user %>
    <%= link_to "Add New Post", new_post_path %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to "Logout", destroy_session_path %>
<% else %>
    <%= link_to "Login", new_session_path %>
<% end %>
<hr>

app/views/users/index.html.erb
<h1 class="jumbotron">Users</h1>

<%= link_to "Add New User", new_user_path %>
&nbsp;&nbsp;|&nbsp;&nbsp;
<% if current_user %>
    <%= link_to "Logout", destroy_session_path %>
<% else %>    
    <%= link_to "Login", new_session_path %>
<% end %>
<hr>

<% flash.each do |key, value| %>
    <div class="alert <%= key %>"><%= value %></div>
<% end %>

<% if @users.count > 0 %>
    <% @users.each do |user| %>
        <h4><%= user.name %><br>
        <small><%= user.email %></small>
        </h4>
        <hr>
    <% end %>
<% else %>
    <h3>No Users Exist</h3>
    <hr>
<% end %>

app/views/users/new.html.erb
<h1 class="jumbotron">Enter New User Info</h1>

<% flash.each do |key, value| %>
    <div class="<%= key %>"><%= value %></div>
<% end %>

<%= form_for @user, url: create_user_path do |f| %>

    <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>
    </div>
    
    <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
    <br>
    <%= f.label :password_confirmation, "Confirm" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <%= f.submit "Register", class: "btn btn-primary" %>

<% end %>